version: "2"

linters:
  enable:
    # Core linters (no duplication with gopls)
    - errcheck        # Comprehensive error checking beyond gopls
    - gocritic        # Performance and style checks

    # Critical additions
    - gosec           # Security issues
    - rowserrcheck    # SQL rows.Err() checks
    - sqlclosecheck   # SQL resource leaks
    - copyloopvar     # Loop variable bugs
    - nilerr          # Nil error returns
    - errorlint       # Error wrapping

    # Code quality
    - unconvert       # Unnecessary conversions
    - wastedassign    # Wasteful assignments
    - misspell        # Spelling

    # Best practices
    - noctx           # Context in HTTP requests
    - bodyclose       # HTTP body closing


  settings:
    gosec:
      excludes:
        - G104  # Duplicate of errcheck
