version: "2"

linters:
  enable:
    # Core linters (no duplication with gopls)
    - errcheck        # Comprehensive error checking beyond gopls
    - gocritic        # Performance and style checks

    # Critical additions
    - gosec           # Security issues
    - rowserrcheck    # SQL rows.Err() checks
    - sqlclosecheck   # SQL resource leaks
    - copyloopvar     # Loop variable bugs
    - nilerr          # Nil error returns
    - errorlint       # Error wrapping

    # Code quality
    - unconvert       # Unnecessary conversions
    - wastedassign    # Wasteful assignments
    - misspell        # Spelling

    # Best practices
    - noctx           # Context in HTTP requests
    - bodyclose       # HTTP body closing


  settings:
    gosec:
      excludes:
        - G104  # Duplicate of errcheck
    revive:
      rules:
        # Explicitly disabled (overlap with gopls staticcheck)
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true

        # Unique revive rules (no overlap with gopls staticcheck)
        - name: context-as-argument
        - name: context-keys-type
        - name: indent-error-flow
        - name: early-return
        - name: defer
        - name: unchecked-type-assertion
        - name: waitgroup-by-value
        - name: modifies-value-receiver

